# Generated by Django 5.2.3 on 2025-07-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimulacionAmbiental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('edad', models.PositiveIntegerField()),
                ('ciudad', models.CharField(max_length=100)),
                ('km_por_dia', models.FloatField()),
                ('medio_transporte', models.CharField(max_length=50)),
                ('carne_por_semana', models.PositiveIntegerField()),
                ('vegetales_por_semana', models.PositiveIntegerField()),
                ('horas_luz_dia', models.FloatField()),
                ('separa_residuos', models.BooleanField()),
            ],
        ),
    ]
